#pragma once

typedef enum {
    SEMA_PATH_SEG_DECL,
    SEMA_PATH_SEG_SIZEOF_TYPE,
    SEMA_PATH_SEG_STRUCT_FIELD,
    SEMA_PATH_SEG_SLICE_PTR,
    SEMA_PATH_SEG_SLICE_LENGTH,
    SEMA_PATH_SEG_EXT_FUNC_HANDLE_DIRECT,
} SemaPathSegKind;
